# Used for tests
version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./test-assets/backend-data/rabbitmq:/var/lib/rabbitmq
    container_name: rabbitmq

  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  # Kafka UI
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

  mosquitto-ssl:
    container_name: mosquitto_container_ssl
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./test-assets/mosquitto-ssl:/mosquitto/config/
    ports:
      - '8883:8883'

  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:1.6.10
    volumes:
      - ./test-assets/mosquitto:/mosquitto/config/
    ports:
      - '1883:1883'
  activemq:
    container_name: activemq
    image: rmohr/activemq:latest
    ports:
      - "61613:61613"
      - "8161:8161" #Admin port, admin/admin to login

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  pulsar:
    image: apachepulsar/pulsar:latest
    ports:
      - "6650:6650"
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone"

  natsjs:
    image: nats:2.7.1-alpine3.15
    ports:
      - "4222:4222" # NATS Port
      - "6222:6222"
      - "8222:8222" # HTTP Monitor
    volumes:
      - ${PWD}/data/jetstream:/data/jetstream
      - ${PWD}/assets/nats-server.conf:/etc/nats/nats-server.conf
