// Code generated by protoc-gen-go. DO NOT EDIT.
// source: status.proto

package pbs

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status struct {
	// A simple error code that can be easily handled by the client. The
	// actual error code is defined by `google.rpc.Code`.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// A developer-facing human-readable error message in English. It should
	// both explain the error and offer an actionable resolution to it.
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfe4fce6682daf5b, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "events.Status")
}

func init() { proto.RegisterFile("status.proto", fileDescriptor_dfe4fce6682daf5b) }

var fileDescriptor_dfe4fce6682daf5b = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0x8e, 0xb1, 0x0a, 0xc2, 0x30,
	0x18, 0x84, 0xa9, 0x68, 0xc5, 0x20, 0x0a, 0x99, 0x3a, 0x16, 0xa7, 0x0e, 0x9a, 0x0c, 0x82, 0x0f,
	0xd0, 0x17, 0x10, 0xea, 0xe6, 0x96, 0xc4, 0x9f, 0x56, 0xb0, 0xfd, 0x43, 0xef, 0x8f, 0xcf, 0x2f,
	0xa4, 0xb8, 0xdd, 0x1d, 0xc7, 0xc7, 0xa7, 0xf6, 0x10, 0x27, 0x09, 0x26, 0xce, 0x2c, 0xac, 0x4b,
	0xfa, 0xd2, 0x24, 0x38, 0xdd, 0x54, 0xf9, 0xc8, 0xbb, 0xd6, 0x6a, 0x1d, 0xf8, 0x45, 0x55, 0x51,
	0x17, 0xcd, 0xa6, 0xcb, 0x59, 0x57, 0x6a, 0x3b, 0x12, 0xe0, 0x7a, 0xaa, 0x56, 0x75, 0xd1, 0xec,
	0xba, 0x7f, 0x6d, 0xef, 0xea, 0x88, 0xc1, 0x78, 0x27, 0x61, 0x30, 0x0b, 0xaa, 0x3d, 0x74, 0x84,
	0xc8, 0x13, 0x68, 0x01, 0x3e, 0xcf, 0xfd, 0x5b, 0x86, 0xe4, 0x4d, 0xe0, 0xd1, 0xe6, 0x63, 0xe0,
	0x39, 0xda, 0xf8, 0x49, 0xa3, 0xa7, 0xd9, 0x0a, 0x41, 0x2e, 0x0e, 0x20, 0x81, 0x8d, 0x1e, 0xbe,
	0xcc, 0x5e, 0xd7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xe3, 0xfc, 0xc9, 0xa7, 0x00, 0x00,
	0x00,
}
